### PR TITLE
Made it available on QGIS

### PR DESCRIPTION
**Pull request by fitoprincipe**
Hi Genna, I don't know if you have tested it but I couldn't open the plugin without this change. I also looked at https://docs.qgis.org/2.18/en/docs/pyqgis_developer_cookbook/plugins.html to see if a `__init__.py` file was still necessary for new QGIS version (I still use 2.14 LTR). I also fixed a typo.

### CODE REVIEW

**Comment by gena** [comment]
It's not ready yet. Will release a preview version once something useful is ready. Stay tuned.

**Comment by fitoprincipe** [comment]
Ok, understand. Have you fixed the typo?

**Comment by gena** [comment]
Ah, thanks for comments :-). I did not expect anyone to react with a pull request so early in the development, nice!

**Comment by fitoprincipe** [comment]
You are welcome. I want to help =)

**Pull request merged**
